# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "usb_storage" "uas" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/077c9a8e-78b1-453c-b3ba-b73797c74007";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/077c9a8e-78b1-453c-b3ba-b73797c74007";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/gaming" =
    { device = "/dev/disk/by-uuid/077c9a8e-78b1-453c-b3ba-b73797c74007";
      fsType = "btrfs";
      options = [ "subvol=@gaming" ];
    };

  fileSystems."/virt-machines" =
    { device = "/dev/disk/by-uuid/077c9a8e-78b1-453c-b3ba-b73797c74007";
      fsType = "btrfs";
      options = [ "subvol=@virt-machines" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/077c9a8e-78b1-453c-b3ba-b73797c74007";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/37C5-1D0A";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
